"""BITV 2.0 / EN 301 549 conformance report of web UI v2.

    python -m tests.a11y.conformance --results a11y-results.json [--llm llm-review.json]
    python -m tests.a11y.conformance --docs

``--results`` takes the per-step results the a11y suite writes with
``ZING_A11Y_RESULTS=<path>`` (tests/a11y/results.py) and writes
``zing/web/static/v2/bitv-report.json`` (``--out`` moves it), which the page
``/v2/accessibility`` renders: per test step (the 50 WCAG 2.1 A/AA criteria,
numbered as EN 301 549 / BITV 9.x.x.x) how it is tested and the latest result.
``--llm`` merges per-step notes of a semi-automated review, if one was made.

``--docs`` rewrites the coverage table in docs/ACCESSIBILITY.md from the
catalogue (zing/web/static/v2/bitv-catalogue.json, the single source of truth)
and the ``@pytest.mark.bitv`` markers of the tests.

Standard library only; it does not need Playwright or a browser.
"""

from __future__ import annotations

import argparse
import ast
import datetime as _dt
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

from tests.a11y.bitv_map import catalogue

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
DEFAULT_OUT = ROOT / "zing" / "web" / "static" / "v2" / "bitv-report.json"
DOCS = ROOT / "docs" / "ACCESSIBILITY.md"
DOCS_START = "<!-- bitv-coverage:start (generated by python -m tests.a11y.conformance --docs) -->"
DOCS_END = "<!-- bitv-coverage:end -->"
SCHEMA = "zing-bitv-report/1"

AUTOMATION = ("auto", "partial", "manual", "n/a")
STATUSES = ("pass", "fail", "not tested", "manual review pending", "n/a")
MAX_FAILURES = 5
MAX_MESSAGE = 600


def _step_key(step: str) -> list[int]:
    return [int(x) for x in step.split(".") if x.isdigit()]


def _short(nodeid: str) -> str:
    """tests/a11y/test_visual.py::test_reflow[de-kb] -> test_reflow[de-kb]"""
    return nodeid.rsplit("::", 1)[-1]


def _func(nodeid: str) -> str:
    return _short(nodeid).split("[", 1)[0]


def _git_commit() -> str | None:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "--short=12", "HEAD"], cwd=ROOT, capture_output=True, text=True, timeout=10, check=True
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return out.stdout.strip() or None


def _zing_version() -> str | None:
    try:
        from zing import __version__

        return str(__version__)
    except ImportError:  # pragma: no cover
        return None


def step_status(automation: str, outcomes: list[str]) -> str:
    """Status of one step from the outcomes of the tests that ran for it."""
    if automation == "n/a":
        return "n/a"
    ran = [o for o in outcomes if o in ("passed", "failed")]
    if "failed" in ran:
        return "fail"
    if ran:
        return "pass" if automation == "auto" else "manual review pending"
    return "manual review pending" if automation == "manual" else "not tested"


def _review_notes(llm: dict[str, Any] | None) -> tuple[dict[str, dict[str, Any]], dict[str, Any] | None]:
    """A semi-automated review file -> ({step: {verdict, notes}}, meta). Accepts
    {"steps": {step: {...} | "note"}}, {"steps": [{"step": ..., ...}]} or a bare
    {step: ...} map; steps may be "9.1.1.1" or WCAG "1.1.1"."""
    if not llm:
        return {}, None
    raw = llm.get("steps", llm) if isinstance(llm, dict) else llm
    items: list[tuple[str, Any]] = []
    if isinstance(raw, dict):
        items = [(str(k), v) for k, v in raw.items() if re.match(r"^\d+(\.\d+)+$", str(k))]
    elif isinstance(raw, list):
        items = [(str(e.get("step") or e.get("wcag") or ""), e) for e in raw if isinstance(e, dict)]
    out: dict[str, dict[str, Any]] = {}
    for step, v in items:
        if not step:
            continue
        if not step.startswith("9."):
            step = "9." + step
        if isinstance(v, dict):
            notes = v.get("notes") or v.get("note") or v.get("summary") or v.get("comment") or v.get("findings") or ""
            verdict = v.get("verdict") or v.get("status") or v.get("result")
        else:
            notes, verdict = v, None
        if isinstance(notes, list):
            notes = "\n".join(str(n) if not isinstance(n, dict) else json.dumps(n, ensure_ascii=False) for n in notes)
        out[step] = {"verdict": str(verdict) if verdict is not None else None, "notes": str(notes)[:4000]}
    meta = {k: llm[k] for k in ("model", "generated_at", "method", "source", "note") if isinstance(llm, dict) and k in llm}
    return out, meta


def _summarize(entries: list[dict[str, Any]]) -> dict[str, Any]:
    counts = {"run": 0, "passed": 0, "failed": 0, "skipped": 0}
    failures: list[str] = []
    seen: set[str] = set()
    for e in entries:
        o = e.get("outcome")
        if o in ("passed", "failed"):
            counts["run"] += 1
        if o in counts:
            counts[o] += 1
        if o == "failed":
            msg = (e.get("message") or "").strip()
            key = msg.split("\n", 1)[0] + "\n" + _func(e["test"])
            if key in seen or len(failures) >= MAX_FAILURES:
                continue
            seen.add(key)
            if len(msg) > MAX_MESSAGE:
                msg = msg[: MAX_MESSAGE - 1] + "…"
            failures.append(f"{_short(e['test'])}: {msg}")
    tests = sorted({_func(e["test"]) for e in entries})
    return {"counts": counts, "failures": failures, "test_names": tests}


def _pct(n: int, d: int) -> float:
    return round(100.0 * n / d, 1) if d else 0.0


def build_report(
    results: dict[str, Any] | None,
    llm: dict[str, Any] | None = None,
    cat: dict[str, Any] | None = None,
    now: _dt.datetime | None = None,
    commit: str | None = None,
) -> dict[str, Any]:
    cat = cat or catalogue()
    results = results or {}
    by_step: dict[str, list[dict[str, Any]]] = results.get("steps") or {}
    review, review_meta = _review_notes(llm)
    steps: list[dict[str, Any]] = []
    for c in cat["steps"]:
        s = _summarize(by_step.get(c["step"], []))
        entry = {
            "step": c["step"], "wcag": c["wcag"], "level": c["level"], "title": c["title"],
            "automation": c["automation"], "how": c["how"],
            "status": step_status(c["automation"], [e.get("outcome", "") for e in by_step.get(c["step"], [])]),
            "tests": s["counts"], "test_names": s["test_names"], "failures": s["failures"],
        }
        if c["step"] in review:
            entry["review"] = review[c["step"]]
        steps.append(entry)
    known = {c["step"] for c in cat["steps"]}
    beyond = []
    for step in sorted(set(by_step) - known, key=_step_key):
        s = _summarize(by_step[step])
        st = "fail" if s["counts"]["failed"] else ("pass" if s["counts"]["passed"] else "not tested")
        beyond.append({"step": step, "status": st, "tests": s["counts"], "test_names": s["test_names"], "failures": s["failures"]})

    applicable = [e for e in steps if e["automation"] != "n/a"]
    n_app = len(applicable)
    automation = {
        a: {"count": sum(1 for e in steps if e["automation"] == a),
            "percent": _pct(sum(1 for e in applicable if e["automation"] == a), n_app) if a != "n/a" else None}
        for a in AUTOMATION
    }
    status = {
        st: {"count": sum(1 for e in steps if e["status"] == st),
             "percent": _pct(sum(1 for e in applicable if e["status"] == st), n_app) if st != "n/a" else None}
        for st in STATUSES
    }
    test_outcomes = [t.get("outcome") for t in (results.get("tests") or {}).values()]
    manual_review = False  # no recorded manual review yet (see docs/ACCESSIBILITY.md)
    all_pass = n_app > 0 and all(e["status"] == "pass" for e in applicable)
    now = now or _dt.datetime.now(_dt.timezone.utc)
    return {
        "schema": SCHEMA,
        "standards": cat["standards"],
        "generated_at": now.isoformat(timespec="seconds"),
        "tests_run_at": results.get("generated_at"),
        "zing_version": _zing_version(),
        "commit": commit,
        "axe_version": results.get("axe_version"),
        "tested": {
            "languages": results.get("langs") or [],
            "themes": results.get("themes") or [],
            "pages": results.get("pages") or {},
        },
        "conformance": {
            "status": "fully conformant" if all_pass and manual_review else "partially conformant",
            "manual_review": manual_review,
        },
        "totals": {
            "steps": len(steps),
            "applicable": n_app,
            "automation": automation,
            "status": status,
            "tests": {
                "run": sum(1 for o in test_outcomes if o in ("passed", "failed")),
                "passed": test_outcomes.count("passed"),
                "failed": test_outcomes.count("failed"),
                "skipped": test_outcomes.count("skipped"),
            },
        },
        "steps": steps,
        "beyond": beyond,
        "review": review_meta if review else None,
    }


# --------------------------------------------------------------------------- #
# docs/ACCESSIBILITY.md coverage table
# --------------------------------------------------------------------------- #
def marked_tests(test_dir: Path = HERE) -> dict[str, list[str]]:
    """Static scan of tests/a11y/test_*.py: step -> test functions marked with it."""
    out: dict[str, list[str]] = {}
    for path in sorted(test_dir.glob("test_*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"))
        consts: dict[str, list[str]] = {}
        for node in tree.body:
            if isinstance(node, ast.Assign) and isinstance(node.value, (ast.Tuple, ast.List)):
                vals = [e.value for e in node.value.elts if isinstance(e, ast.Constant) and isinstance(e.value, str)]
                for t in node.targets:
                    if isinstance(t, ast.Name):
                        consts[t.id] = vals
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) or not node.name.startswith("test"):
                continue
            for d in node.decorator_list:
                if not (isinstance(d, ast.Call) and isinstance(d.func, ast.Attribute) and d.func.attr == "bitv"):
                    continue
                for a in d.args:
                    vals = (
                        consts.get(a.value.id, []) if isinstance(a, ast.Starred) and isinstance(a.value, ast.Name)
                        else [a.value] if isinstance(a, ast.Constant) and isinstance(a.value, str) else []
                    )
                    for v in vals:
                        lst = out.setdefault(v, [])
                        if node.name not in lst:
                            lst.append(node.name)
    return out


def docs_table(cat: dict[str, Any] | None = None, tests: dict[str, list[str]] | None = None) -> str:
    cat = cat or catalogue()
    tests = marked_tests() if tests is None else tests
    lines = [
        "| Step | WCAG 2.1 | Level | Title | Automation | How | Tests |",
        "|---|---|---|---|---|---|---|",
    ]
    for c in cat["steps"]:
        names = ", ".join(f"`{t}`" for t in tests.get(c["step"], [])) or "—"
        how = c["how"].replace("|", "\\|")
        lines.append(f"| {c['step']} | {c['wcag']} | {c['level']} | {c['title']} | {c['automation']} | {how} | {names} |")
    extra = sorted(set(tests) - {c["step"] for c in cat["steps"]}, key=_step_key)
    for step in extra:
        names = ", ".join(f"`{t}`" for t in tests[step])
        lines.append(f"| {step} | — | — | beyond WCAG (EN 301 549 clause {step}) | auto | — | {names} |")
    return "\n".join(lines)


def update_docs(path: Path = DOCS) -> bool:
    text = path.read_text(encoding="utf-8")
    if DOCS_START not in text or DOCS_END not in text:
        raise SystemExit(f"{path}: coverage table markers not found")
    head, rest = text.split(DOCS_START, 1)
    _, tail = rest.split(DOCS_END, 1)
    new = f"{head}{DOCS_START}\n{docs_table()}\n{DOCS_END}{tail}"
    if new != text:
        path.write_text(new, encoding="utf-8")
        return True
    return False


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="python -m tests.a11y.conformance", description=__doc__.split("\n\n")[0])
    ap.add_argument("--results", type=Path, help="per-step results written by the a11y suite (ZING_A11Y_RESULTS)")
    ap.add_argument("--llm", type=Path, help="optional semi-automated review notes per step")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"report to write (default: {DEFAULT_OUT.relative_to(ROOT)})")
    ap.add_argument("--docs", action="store_true", help="rewrite the coverage table in docs/ACCESSIBILITY.md")
    args = ap.parse_args(argv)
    if not args.results and not args.docs:
        ap.error("give --results and/or --docs")
    if args.docs:
        print(("updated " if update_docs() else "unchanged ") + str(DOCS.relative_to(ROOT)))
    if args.results:
        results = json.loads(args.results.read_text(encoding="utf-8")) if args.results.exists() else None
        if results is None:
            print(f"warning: {args.results} not found, every step is reported as not tested", file=sys.stderr)
        llm = None
        if args.llm:
            if args.llm.exists():
                llm = json.loads(args.llm.read_text(encoding="utf-8"))
            else:
                print(f"warning: {args.llm} not found, no review notes merged", file=sys.stderr)
        report = build_report(results, llm, commit=_git_commit())
        args.out.write_text(json.dumps(report, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        t = report["totals"]
        print(
            f"wrote {args.out}: {t['status']['pass']['count']} pass, {t['status']['fail']['count']} fail, "
            f"{t['status']['not tested']['count']} not tested, "
            f"{t['status']['manual review pending']['count']} manual review pending, {t['status']['n/a']['count']} n/a"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
